# Generated by Django 3.1.4 on 2020-12-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('article_url', models.URLField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('posted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('translator', models.CharField(blank=True, max_length=255, null=True)),
                ('editor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
