import os
import scrapy
import django
from datetime import datetime
from w3lib.html import remove_tags

# Make it possible to run the spider from the project root
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from scraper.spiders.helpers import parse_article
from articles.models import Article


class UNDPSpider(scrapy.Spider):
    name = "undp"
    start_urls = [
        "https://www.undp.org/ky/kyrgyzstan/blog/kyrgyzstanda-sanariptik-zhetkiliktuuluktu-onukturuu",
        "https://www.undp.org/ky/kyrgyzstan/stories/inklyuzivduu-koom",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstan-onduruuchulorun-koldoo-ataandashtykka-zhondomduuluktu-kuchotuu-zhana-eksporttuk-mumkunchuluktordu-keneytuu",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstandyk-balchylardyn-iygiligi-toguz-bulak-ayylynan-zhayloobay-bektursunovdun-tazhryybasy",
        "https://www.undp.org/ky/kyrgyzstan/blog/zharatman-ayymdar-zhamaaty-zhe-buuop-kreativduu-meykindikter-arkyluu-ayaldardyn-mumkunchuluktorun-keneytuugo-kantip-komoktoshot",
        "https://www.undp.org/ky/kyrgyzstan/stories/borbor-aziya-uchun-tom-platformasy-uran-murasyn-chechuugo-evrobirimdik-kandaycha-zhardam-berip-zhatat",
        "https://www.undp.org/ky/kyrgyzstan/stories/maalymat-tekhnologiyalar-zhaatynda-oogan-kyz-kelinderinin-mumkunchuluktorun-keneytuu-0",
        "https://www.undp.org/ky/kyrgyzstan/stories/maalymat-tekhnologiyalar-zhaatynda-oogan-kyz-kelinderinin-mumkunchuluktorun-keneytuu",
        "https://www.undp.org/ky/kyrgyzstan/blog/buuop-kyrgyzstandagy-kreativduu-ekonomikanyn-darametin-achuuda",
        "https://www.undp.org/ky/kyrgyzstan/blog/1-aprel-kanattuulardyn-el-aralyk-kunu",
        "https://www.undp.org/ky/kyrgyzstan/stories/energetikadagy-ayaldar",
        "https://www.undp.org/ky/kyrgyzstan/stories/borborduk-aziyadagy-klimattyn-ozgorushu-zhana-turuktuuluk",
        "https://www.undp.org/ky/kyrgyzstan/stories/zhany-mumkunchuluktor-zhana-umuttor-ort-ochuruuchu-bektur-shamshievdin-okuyasy",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstandyn-zharyktangan-ayyldar-kayyrkul-kurmanbekovna-bakytaevanyn-sayakaty",
        "https://www.undp.org/ky/kyrgyzstan/stories/progressti-kubattandyruu-gulnara-khasenovanyn-energetikalyk-bashkaruudagy-sayakaty",
        "https://www.undp.org/ky/kyrgyzstan/stories/taza-energiyany-keneytuu-kundus-kyrbashevanyn-bayandamasy",
        "https://www.undp.org/ky/kyrgyzstan/stories/valentina-makhmutovna-kasymova-energetika-tarmagynyn-algachky-otlichnigi",
        "https://www.undp.org/ky/kyrgyzstan/stories/tatyana-vedeneva-zhanylanuuchu-energiya-bulaktaryn-zhana-energiya-natyyzhaluulugun-onukturuu-borborunun-prezidenti",
        "https://www.undp.org/ky/kyrgyzstan/stories/zhergiliktuu-turgundardy-zhana-zharandyk-koomdu-shaardyn-zhashoosuna-aktivduu-tartuu-chyr-chataktardyn-aldyn-aluu-zhaatynda",
        "https://www.undp.org/ky/kyrgyzstan/stories/socialdyk-chynaluularga-monitoring-zhurguzuu-zhana-alardy-chechuu-processterine-zhashtardyn-katyshuusu",
        "https://www.undp.org/ky/kyrgyzstan/stories/etnostor-aralyk-maseleler-boyuncha-koomduk-kabyldamanyn-ishi-adamdardyn-zhashoosundagy-ozgoruulordun-chakan-okuyalary",
        "https://www.undp.org/ky/kyrgyzstan/stories/stigmaga-karshy-birge-turabyz",
        "https://www.undp.org/ky/kyrgyzstan/blog/maksattardan-ish-araketke-kyrgyz-respublikasynda-insandyk-onuguunun-otkon-kez-azyrky-abaly-zhana-kelechegi",
        "https://www.undp.org/ky/kyrgyzstan/stories/tokmok-shaarynyn-zhashtaryna-madaniy-baaluuluktardy-kalyptandyruu-zhana-koomduk-dialogdu-zhurguzuu-kondumdoru-iygiliktuu-otup",
        "https://www.undp.org/ky/kyrgyzstan/stories/adam-ukuktary-zhaatynda-zhoopkerchiliktuu-zhurum-turum-standarttaryn-zhayyltuudagy-biznes-associaciyalardyn-rolu",
        "https://www.undp.org/ky/kyrgyzstan/stories/biznes-uchun-nuskama-kompaniya-zhergiliktuu-koomchuluk-menen-baylanyshuuda-kaysy-suroolorgo-zhoop-berishi-kerek",
        "https://www.undp.org/ky/kyrgyzstan/stories/adam-ukuktary-boyuncha-korporativdik-sayasat-al-emne-uchun-maaniluu-zhana-emneden-bashtoo-kerek",
        "https://www.undp.org/ky/kyrgyzstan/stories/biznestin-zhoopkerchiliktuu-zhurum-turumu-kyrgyzstan-uchun-chakyryktar-zhana-mumkunchuluktor",
        "https://www.undp.org/ky/kyrgyzstan/stories/kompaniyalardyn-adam-ukuktary-zhaatyndagy-tiyishtuu-etiyattygy-eb-olkolorunun-zhana-yaponiyanyn-mamlekettik-zhongo-saluu",
        "https://www.undp.org/ky/kyrgyzstan/stories/biznes-zhana-adam-ukuktary-boyuncha-buunun-zhetektoochu-principteri",
        "https://www.undp.org/ky/kyrgyzstan/stories/bizneste-adam-ukuktarynyn-urmattalyshyna-ukuk-korgoochulardyn-salymy",
        "https://www.undp.org/ky/kyrgyzstan/stories/zhoopkerchiliktuu-zhurum-turum-korsotkuchtoru-kompaniya-ozun-kantip-teksheruusu-kerek",
        "https://www.undp.org/ky/kyrgyzstan/stories/akyykatchy-apparatynyn-ishkerlik-zhana-adam-ukuktary-boyuncha-kun-tartibin-ilgerletuugo-koshkon-salymy",
        "https://www.undp.org/ky/kyrgyzstan/stories/ishkanada-dattanuu-mekhanizmi-anyn-natyyzhaluulugun-arttyruu-zholdoru",
        "https://www.undp.org/ky/kyrgyzstan/stories/ken-ondurushu-zhana-adam-ukuktary-profsoyuzdar-biznesti-zhoopkerchiliktuu-alyp-baruunun-kuzotundo",
        "https://www.undp.org/ky/kyrgyzstan/stories/emgek-ministrliginin-biznes-zhana-adam-ukuktary-kun-tartibine-koshkon-salymy",
        "https://www.undp.org/ky/kyrgyzstan/stories/16-zhashynda-ozu-shyktuu-kesibin-tapkan-aybiyke-bolotovanyn-okuyasy",
        "https://www.undp.org/ky/kyrgyzstan/stories/ayzat-sanarip-ayymdar-dolbooruna-katyshyp-portfoliosu-uchun-uch-veb-saytty-ishtep-chygyp-zhumushka-ornoshup-buyrutmalardy-kabyl",
        "https://www.undp.org/ky/kyrgyzstan/stories/sanarip-ayymdar-dolbooru-aydanektin-zhashoosuna-oluttuu-ozgoruulordu-alyp-keldi",
        "https://www.undp.org/ky/kyrgyzstan/stories/sanarip-ayymdar-mirbek-kyzy-madinanyn-bardyk-korkuularyn-zhok-kylyp-any-duynodogu-en-mykty-it-adisterinin-biri-boluuga",
        "https://www.undp.org/ky/kyrgyzstan/stories/sanarip-ayymdar-dolbooru-elinaga-ozun-tabuuga-zhana-medicina-menen-smmdi-iygiliktuu-aykalyshtyruuga-mumkunduk-berdi",
        "https://www.undp.org/ky/kyrgyzstan/stories/maga-orusiyadan-da-chon-zakazdar-kele-bashtady-oshonduktan-cekh-achtym-bul-menin-kareramdagy-maaniluu-kadam-boldu",
        "https://www.undp.org/ky/kyrgyzstan/stories/dekret-iygilikke-toskool-zharatpayt",
        "https://www.undp.org/ky/kyrgyzstan/stories/sanarip-ayymdar-dolbooru-aygerim-usupbekovaga-sanariptik-ishke-ornoshuu-mumkunchuluktordun-duynosunun-eshigin-achkandygy-tuuraluu",
        "https://www.undp.org/ky/kyrgyzstan/blog/mayyptyktyn-massalyk-maalymat-karazhattarynda-chagyldyrylyshy-undor-uguldu",
        "https://www.undp.org/ky/kyrgyzstan/stories/mektep-okuuchusu-balkyyal-tazhibaevanyn-onorun-orkundotup-ozuno-kolunan-baary-keleerin-dalildegen-bayany",
        "https://www.undp.org/ky/kyrgyzstan/blog/bugun-abdan-suluusuz-degen-soz-kesipteshke-karata-koduloobu-zhe-komplimentpi",
        "https://www.undp.org/ky/kyrgyzstan/stories/stem4all-kesipterdin-kelechegi-uchun",
        "https://www.undp.org/ky/kyrgyzstan/blog/landshafttyk-baylanysh-batysh-tyan-shanda-turuktuu-bioturduuluktu-saktoonun-achkychy",
        "https://www.undp.org/ky/kyrgyzstan/stories/bangizatka-koz-karandy-adamdar-sapattuu-medicinalyk-zhana-socialdyk-kyzmat-korsotuulordu-aluuga-ukuktuu",
        "https://www.undp.org/ky/kyrgyzstan/stories/ayguldun-bayany-zhe-buuop-kyrgyzstandyn-alysky-aymaktarynda-sanariptik-kondumdordu-zhana-sanaripteshtiruunu-tezdetuunu-kantip",
        "https://www.undp.org/ky/kyrgyzstan/stories/khimaya-ayaldardy-korgoo-zhana-vich-menen-kuroshuu",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstanda-kurgak-uchuk-menen-birgeleshken-kurosh",
        "https://www.undp.org/ky/kyrgyzstan/stories/sen-oturup-chykkansyn-unchukpay-chyda-kalktyn-ozoktuk-toptoruna-kirgen-ayaldar-kantip-zombulukka-tush-bolup-korkuu-sezimderin",
        "https://www.undp.org/ky/kyrgyzstan/stories/kastyk-tilinen-zombuluksuz-kommunikaciyaga",
        "https://www.undp.org/ky/kyrgyzstan/blog/turuktuu-onuguu-zholunda-kuch-araketterdi-biriktiruu-kyrgyz-respublikasynda-kukm-ishke-ashyrylyshy",
        "https://www.undp.org/ky/kyrgyzstan/blog/kyrgyz-respublikasyndagy-insandyn-onuguusu-boyuncha-uluttuk-bayandamacy-klimattyk-ozgoruu-shartynda-turuktuu-zhana-adilettuu",
        "https://www.undp.org/ky/kyrgyzstan/blog/kyrgyzstandagy-buuoptun-zhashtar-menen-atkargan-oluttuu-ishteri",
        "https://www.undp.org/ky/kyrgyzstan/stories/klimattyk-terminderdin-sozdugu-klimattyn-ozgorushu-maseleleri-boyuncha-kunumduk-maalymdama",
        "https://www.undp.org/ky/kyrgyzstan/stories/sanarip-kondumdor-bibigulgo-kyyalyndagy-karerasyna-zhol-achty",
        "https://www.undp.org/ky/kyrgyzstan/blog/zharatman-ayymdar-zhamaaty-buuop-kyrgyzstandagy-ayymdardyn-chygarmachyl-bagyttagy-onuguusun-belgilep-ottu",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstanda-ayaldardyn-ilimdi-onukturuugo-koshkon-salymy-belgilenuudo",
        "https://www.undp.org/ky/kyrgyzstan/blog/emgek-choyrosunun-tatyktuu-kelechegin-kamsyz-kyluu-uchun-buuopnyn-kyrgyzstandagy-okulchulugu-stem-tarmagynda-ayaldardyn",
        "https://www.undp.org/ky/kyrgyzstan/blog/buuoptun-innovaciyalyk-sanariptik-transformaciyasy-kyrgyzstandyn-misaly",
        "https://www.undp.org/ky/kyrgyzstan/stories/air-quality-bishkek",
        "https://www.undp.org/ky/kyrgyzstan/stories/batken-oblastynyn-klimatka-turuktuulugun-kuchotuu",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyz-zharany-koncepciyasynyn-etnostor-aralyk-zhana-diniy-mamilelerge-tiygizgen-taasiri-attuu-sociologiyalyk-izildoonun",
        "https://www.undp.org/ky/kyrgyzstan/stories/uy-ashpozchusunan-biznes-ledige-karay",
        "https://www.undp.org/ky/kyrgyzstan/stories/ensegen-kyyalga-karay",
        "https://www.undp.org/ky/kyrgyzstan/stories/sanzhar-abdimalikov-25-zhashynda-6-zhumush-ordun-achkan",
        "https://www.undp.org/ky/kyrgyzstan/stories/zhergiliktuu-zhamaattardy-tartuu-arkyluu-aylana-choyronu-korgoogo-komok-korsotuu",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstandyktar-kriptovalyuta-zhana-web-30-duynosundo",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstanda-onuguunu-karzhyloogo-birinchi-baa-beriluudo",
        "https://www.undp.org/ky/kyrgyzstan/stories/salyktyk-zhenildikter-kyrgyzstanda-tomgo-zhetishuugo-zhardam-beret",
        "https://www.undp.org/ky/kyrgyzstan/stories/emgekti-suyuuchuluk-zhana-kesipkoyluk-ishkerge-leylekte-chakan-ishkana-kuruuga-zhardam-berdi",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyrgyzstandyk-bilim-beruu-dolbooru-kandaycha-boost-el-aralyk-synagynyn-katyshuuchusu-bolup-kaldy",
        "https://www.undp.org/ky/kyrgyzstan/stories/maftuna-khayitova-kununo-100doy-uy-bulonu-nan-menen-kamsyz-kyluudabyz",
        "https://www.undp.org/ky/kyrgyzstan/stories/kreativduu-turizm-zhonundo-bul-emne-zhana-emne-uchun-kyrgyzstanda-koomchuluktun-onugushuno-zhardam-bere-alat",
        "https://www.undp.org/ky/kyrgyzstan/stories/ayaldar-erkekterge-karaganda-ese-zhakshyraak-ishteshi-kerek-elvira-surabaldieva",
        "https://www.undp.org/ky/kyrgyzstan/stories/narynda-biznesti-noldon-bashtap-any-olko-boyuncha-zhana-chet-olkolordo-kantip-zhayyltuuga-bolot",
        "https://www.undp.org/ky/kyrgyzstan/blog/osh-shaaryndagy-kreativduu-laboratoriyanyn-ishke-kirishi-zhe-talant-toleranttuuluk-zhana-tekhnologiya-zhamaattardy-kantip-bekemdey",
        "https://www.undp.org/ky/kyrgyzstan/stories/eb-buu-tedik-nuru-birgeleshken-demilgesi-zhumush-ordunda-zorduk-zombulukka-zhana-ydyk-korsotuugo-karshy-kampaniyany-koldoyt",
        "https://www.undp.org/ky/kyrgyzstan/blog/genderdik-tenchilik-turuktuu-ekonomikalyk-osuugo-kantip-alyp-kelet",
        "https://www.undp.org/ky/kyrgyzstan/blog/kyrgyzstan-genderdik-tenchilik-arkyluu-kantip-karzhy-tarta-alat",
        "https://www.undp.org/ky/kyrgyzstan/stories/khobbini-bizneske-aylandyruu-kyyyn-emes",
        "https://www.undp.org/ky/kyrgyzstan/stories/volodya-aiv-menen-kuroshtogu-tuboluk-aktivist",
        "https://www.undp.org/ky/kyrgyzstan/stories/ayyl-turgundarynyn-medicinalyk-teyloogo-zhetkiliktuulugun-kamsyz-kyluu",
        "https://www.undp.org/ky/kyrgyzstan/stories/chynara-aiv-menen-kuroshto-sungan-kol",
        "https://www.undp.org/ky/kyrgyzstan/stories/ruslan-aivge-karabastan-optimizmge-toltura",
        "https://www.undp.org/ky/kyrgyzstan/stories/erzhan-uulum-uchun-aiv-menen-kuroshom",
        "https://www.undp.org/ky/kyrgyzstan/stories/zhash-ishkerdin-kyzmatyna-suroo-talap-kop",
        "https://www.undp.org/ky/kyrgyzstan/stories/mumkunchuluktor-izdegenge-achylat",
        "https://www.undp.org/ky/kyrgyzstan/blog/pikir-kyrgyz-respublikasynyn-klimattyk-plany-el-aralyk-kyzmattashttyk-uchun-sharttardy-tuzot",
        "https://www.undp.org/ky/kyrgyzstan/stories/kirov-ayylyndagy-algachky-kinoteatrdyn-tarzhymaly",
        "https://www.undp.org/ky/kyrgyzstan/stories/emi-ozgon-taza-suunu-gana-ichet",
        "https://www.undp.org/ky/kyrgyzstan/stories/maalymat-sistemalary-zhergiliktuu-aymaktarda-kyzmat-aluunu-zhenildetet",
        "https://www.undp.org/ky/kyrgyzstan/stories/oshto-kantip-balchylykty-onukturup-chet-olkolorgo-eksporttun-kolomun-koboytup-zhatyshat",
        "https://www.undp.org/ky/kyrgyzstan/stories/oz-ubagyndagy-dartty-anyktoo-omurlordu-saktayt",
        "https://www.undp.org/ky/kyrgyzstan/stories/ozgondun-bala-bakchasynda-kun-kollektoru-ornotuldu-ysyk-suu-maselesi-chechildi",
        "https://www.undp.org/ky/kyrgyzstan/stories/ozgondogu-ayyl-kantip-koopsuz-zhana-yngayluu-boldu",
        "https://www.undp.org/ky/kyrgyzstan/stories/nookatta-suroo-talapka-zhoop-bergen-tokar-adisterdi-dayardap-zhatyshat",
        "https://www.undp.org/ky/kyrgyzstan/stories/meerguldun-konok-uyu",
        "https://www.undp.org/ky/kyrgyzstan/blog/beyokmot-uyumdar-zhamaattar-zhana-buuoptun-koldoosu-vichke-karshy-kuroshuudo-negizgi-roldu-oynoyt",
        "https://www.undp.org/ky/kyrgyzstan/blog/kyrgyzstandyn-zhash-muundary-olkonun-turuktuu-onuguusunun-negizi",
        "https://www.undp.org/ky/kyrgyzstan/blog/zhergiliktuu-turgundar-zharatylyshka-klimatka-zhana-ekonomikaga-baylanyshtuu-maaniluu-globaldyk-ozgoruulordu-alyp-baryshat",
        "https://www.undp.org/ky/kyrgyzstan/blog/blog-zhumushka-ornoshuuga-toskool-bolgon-socialdyk-tarmaktagy-5-kata",
        "https://www.undp.org/ky/kyrgyzstan/blog/teoriyadan-praktikaga-kyrgyzstandagy-zharandar-oz-zhamaattarynyn-onuguusun-kantip-tezdetishet",
        "https://www.undp.org/ky/kyrgyzstan/stories/kyzymdyn-ukugu",
        "https://www.undp.org/ky/kyrgyzstan/blog/turuktuu-zhamaattardy-kuruuda-kochmon-baaluuluktarynyn-achylbagan-potencialy",
        "https://www.undp.org/ky/kyrgyzstan/blog/emgek-zhana-ekonomikalyk-potencialyn-koldono-algan-ayyldyk-ayaldar-oto-az",
        "https://www.undp.org/ky/kyrgyzstan/blog/kyrgyzstandagy-shayloo-demokratiya-zhana-inklyuzivduuluktun-synagy-bolmokchu",
        "https://www.undp.org/ky/kyrgyzstan/blog/shayloolorgo-cheyin-uch-zhuma-shayloolorgo-dayardanuu-kundolugu",
        "https://www.undp.org/ky/kyrgyzstan/blog/shayloogo-cheyinki-tort-zhuma-shayloogo-dayardanuunun-kundolugu",
        "https://www.undp.org/ky/kyrgyzstan/blog/shayloogo-cheyinki-5-zhuma-shayloogo-dayardanuu-kundolugu",
        "https://www.undp.org/ky/kyrgyzstan/blog/shayloogo-cheyinki-alty-zhuma-shayloogo-dayardanuu-kundolugu",
        "https://www.undp.org/ky/kyrgyzstan/blog/shayloogo-cheyinki-zheti-zhuma-shayloogo-dayardanuu-kundolugu",
        "https://www.undp.org/ky/kyrgyzstan/blog/shayloo-processine-dayardanuu-kundolugu-shayloogo-cheyinki-segiz-zhuma",
        "https://www.undp.org/ky/kyrgyzstan/blog/zhashtar-laboratoriyasy-2020-taza-zhana-akyykat-shayloo-uchun",
        "https://www.undp.org/ky/kyrgyzstan/blog/medicina-kyzmatkerleri-covid-19-uchurunda-oz-zhumushun-kantip-atkaryp-zhatyshat",
        "https://www.undp.org/ky/kyrgyzstan/blog/covid-19-uchurunda-biz-kurgak-uchuktu-daryloogo-mamileni-kantip-almashtyrdyk",
        "https://www.undp.org/ky/kyrgyzstan/blog/kandaycha-stigma-aiv-infekciyasyn-kurgak-uchuktu-zhana-bashka-oorulardy-zhoyuuda-zhol-tosuuda",
        "https://www.undp.org/ky/kyrgyzstan/blog/covid-19-uchurunda-bizdin-beneficiarlar-tuuraluu-tynchsyzdanuumdun-sebebi",
        "https://www.undp.org/ky/kyrgyzstan/blog/bizdin-beneficiarlardyn-zhadagalsa-pasporttoru-da-zhok-buuop-covid-19-uchurunda-tobokel-toptorgo-kandaycha-zhardam-beruudo",
        "https://www.undp.org/ky/kyrgyzstan/blog/pandemiya-menen-kuroshuudo-sanarip-tekhnologiyalar-kandaycha-zhardam-berip-zhatat",
        "https://www.undp.org/ky/kyrgyzstan/stories/metadon-islamdy-bangizatka-koz-karandylyktan-saktap-kaldy",
        "https://www.undp.org/ky/kyrgyzstan/blog/parlamenttik-kozomoldu-kuchotuu-2030-zhylga-cheyinki-kun-tartipti-zhuzogo-ashyruuda-krnyn-progressin-koldoyt",
        "https://www.undp.org/ky/kyrgyzstan/blog/genderdik-tendik-programmasynyn-altyn-muchosu-boluu-tazhryybasy",
    ]

    # TODO: implement the rest
